language: ruby
sudo: false

bundler_args: --without production

jobs:
  include:
    - stage: rubocop
      script:
        - bundle exec rubocop -D -c .rubocop.yml
    - stage: Test
      script:
        - JENKINS=true bundle exec rspec --profile --order rand -f d
